language: haskell
install:  cabal install --enable-benchmarks
script:   cabal configure --enable-benchmarks && \
          cabal build && \
          cabal bench --benchmark-options="+RTS -N"
notifications:
  email:
    - kim.altintop@gmail.com
